apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: tweetviewer
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/cloudylabs-public/tweetviewer:0.2.1
            env:
              - name: RELEASE
                value: "v0.2.1-manual"
              - name: SEARCH
                value: "knative"
